name: Release Builds

on:
    release:
        types: [published]

permissions:
    contents: write

jobs:
    build:
        strategy:
            matrix:
                include:
                    # WINDOWS
                    - os: ubuntu-latest
                      build_type: windows
                      build_arch: x64
                    - os: macos-latest
                      build_type: windows
                      build_arch: arm64
                    # MACOS
                    - os: ubuntu-latest
                      build_type: macos
                      build_arch: x64
                    - os: macos-latest
                      build_type: macos
                      build_arch: arm64
                    # LINUX
                    - os: ubuntu-latest
                      build_type: linux
                      build_arch: x64
                    - os: macos-latest
                      build_type: linux
                      build_arch: arm64
                    # ALPINE
                    - os: ubuntu-latest
                      build_type: alpine
                      build_arch: x64
                    - os: macos-latest
                      build_type: alpine
                      build_arch: arm64
        runs-on: ${{ matrix.os }}
        steps:
            - name: Checkout
              uses: actions/checkout@v6
            - name: Set up Node.js
              uses: actions/setup-node@v6
              with:
                  node-version: 24
                  check-latest: true
            - name: Install 7zip
              run: |
                  if [ "$RUNNER_OS" == "Linux" ]; then
                    sudo apt-get update && sudo apt-get install -y p7zip-full
                  elif [ "$RUNNER_OS" == "macOS" ]; then
                    brew install p7zip
                  fi
              shell: bash
            - name: Install Node modules
              run: npm install
            - name: Get name and version from package.json
              run: |
                  test -n $(node -p -e "require('./package.json').name") &&
                  test -n $(node -p -e "require('./package.json').version") &&
                  echo PACKAGE_NAME=$(node -p -e "require('./package.json').name") >> $GITHUB_ENV &&
                  echo PACKAGE_VERSION=$(node -p -e "require('./package.json').version") >> $GITHUB_ENV || exit 1
            - name: Make build
              run: npm run build-${{ matrix.build_type }}-${{ matrix.build_arch }}-cli
            - name: Upload assets to the GitHub Release
              uses: softprops/action-gh-release@v2
              with:
                  files: |
                      ./lib/_builds/hanimdl-${{ matrix.build_type }}-${{ matrix.build_arch }}-cli.7z
                      ./lib/_builds/hanimdl-${{ matrix.build_type }}-${{ matrix.build_arch }}-cli.7z.sha256
                  fail_on_unmatched_files: true
